name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pkg
        run: npm install -g pkg

      - name: Build EXE
        run: pkg index.js --target node18-win-x64 --output npm-start-service.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-start-service
          path: npm-start-service.exe
